---
Name: myroutes
After: '#modelascontrollerroutes'
---
Director:
  rules:
    '': 'HomeController'
    'profile//$Action/$ID/$OtherID': 'ProfileController'
    'api/todos//$Action/$TodoID': 'TodosController'